In [35]:
source_path = '../files/sources'
gene_diseases_path = f'{source_path}/CTD_curated_genes_diseases.csv'
disease_pathway_path = f'{source_path}/CTD_diseases_pathways.csv'
gobp_disease_path = f'{source_path}/CTD_Phenotype-Disease_biological_process_associations.tsv'

In [ ]:
import pandas as pd

column_names = ['GeneSymbol', 'GeneID', 'DiseaseName', 'DiseaseID', 'OmimIDs', 'PubMedIDs']

gene_diseases_df = pd.read_csv(gene_diseases_path, skiprows=29, names=column_names)

gene_diseases_df_AD = gene_diseases_df[gene_diseases_df["DiseaseName"].str.lower().str.startswith("alzheimer disease", na=False)].reset_index(drop=True)
gene_diseases_df_PD = gene_diseases_df[gene_diseases_df["DiseaseName"].str.lower().str.startswith("parkinson disease", na=False)].reset_index(drop=True)

gene_diseases_df_PD

,GeneSymbol,GeneID,DiseaseName,DiseaseID,OmimIDs,PubMedIDs
0,ABCB1,5243,Parkinson Disease,MESH:D010300,NaN,20558393
1,ABCB1,5243,"Parkinson Disease, Secondary",MESH:D010302,NaN,26457621
2,ADARB2,105,Parkinson Disease,MESH:D010300,NaN,25475535
3,ADH1C,126,"PARKINSON DISEASE, LATE-ONSET",OMIM:168600,168600,NaN
4,AIF1,199,Parkinson Disease,MESH:D010300,NaN,19276553
...,...,...,...,...,...,...
141,UCHL1,7345,"PARKINSON DISEASE 5, AUTOSOMAL DOMINANT, SUSCE...",OMIM:613643,613643,NaN
142,UP,104073,Parkinson Disease,MESH:D010300,NaN,18353766
143,VPS13C,54832,"PARKINSON DISEASE 23, AUTOSOMAL RECESSIVE EARL...",OMIM:616840,616840,NaN
144,VPS35,55737,Parkinson Disease,MESH:D010300,NaN,25149416
145,VPS35,55737,PARKINSON DISEASE 17,OMIM:614203,614203,NaN

In [21]:
column_names = ['DiseaseName', 'DiseaseID', 'PathwayName', 'PathwayID', 'InferenceGeneSymbol']

disease_pathway_df = pd.read_csv(disease_pathway_path, skiprows=29, names=column_names)

disease_pathway_df_AD = disease_pathway_df[disease_pathway_df["DiseaseName"].str.lower().str.startswith("alzheimer disease", na=False)].reset_index(drop=True)
disease_pathway_df_PD = disease_pathway_df[disease_pathway_df["DiseaseName"].str.lower().str.startswith("parkinson disease", na=False)].reset_index(drop=True)

disease_pathway_df_AD

,DiseaseName,DiseaseID,PathwayName,PathwayID,InferenceGeneSymbol
0,Alzheimer Disease,MESH:D000544,ABC-family proteins mediated transport,REACT:R-HSA-382556,ABCA7
1,Alzheimer Disease,MESH:D000544,ABC-family proteins mediated transport,REACT:R-HSA-382556,EIF2S1
2,Alzheimer Disease,MESH:D000544,ABC transporters,KEGG:hsa02010,ABCA7
3,Alzheimer Disease,MESH:D000544,ABC transporters in lipid homeostasis,REACT:R-HSA-1369062,ABCA7
4,Alzheimer Disease,MESH:D000544,Acetylcholine Binding And Downstream Events,REACT:R-HSA-181431,CHRNA7
...,...,...,...,...,...
1911,Alzheimer disease type 4,MESH:C536596,Signal Transduction,REACT:R-HSA-162582,APOE
1912,Alzheimer disease type 4,MESH:C536596,Signal Transduction,REACT:R-HSA-162582,PSEN2
1913,Alzheimer disease type 4,MESH:C536596,Transcriptional regulation by the AP-2 (TFAP2)...,REACT:R-HSA-8864260,APOE
1914,Alzheimer disease type 4,MESH:C536596,Vesicle-mediated transport,REACT:R-HSA-5653656,APOE
1915,Alzheimer disease type 4,MESH:C536596,Visual phototransduction,REACT:R-HSA-2187338,APOE

In [47]:
column_names = ['GOName', 'GOID', 'DiseaseName', 'DiseaseID', 'InferenceChemicalQty', 'InferenceChemicalNames', 'InferenceGeneQty', 'InferenceGeneSymbols']

gobp_disease_df = pd.read_csv(gobp_disease_path, skiprows=29, names=column_names, sep='\t')

gobp_disease_df_AD = gobp_disease_df[gobp_disease_df["DiseaseName"].str.lower().str.startswith("alzheimer disease", na=False)].reset_index(drop=True)
gobp_disease_df_PD = gobp_disease_df[gobp_disease_df["DiseaseName"].str.lower().str.startswith("parkinson disease", na=False)].reset_index(drop=True)

gobp_disease_df_AD[~gobp_disease_df_AD['InferenceGeneSymbols'].isna()]

all_genes = gobp_disease_df_AD["InferenceGeneSymbols"].dropna().str.split("|")
gene_set = set(gene for sublist in all_genes for gene in sublist)

all_gos = gobp_disease_df_AD["GOID"].tolist()
go_set = set(all_gos)

In [64]:
uniprot_go_path = f'{source_path}/UniProtKB-Alzheimer.tsv'
uniprot_go_df = pd.read_csv(uniprot_go_path, sep='\t')

all_uniprot_gos = uniprot_go_df['Gene Ontology IDs'].dropna().str.split(';')
uniprot_go_set = set(gene.strip() for sublist in all_uniprot_gos for gene in sublist)

print(f"Numero di GO in CDT: {len(go_set)}")
print(f"Numero di GO in UniProt: {len(uniprot_go_set)}")
print(f"Numero di GO non attinenti a AD: {len(uniprot_go_set - go_set)}")
print(f"Numero di GO in attinenti ad AD: {len(uniprot_go_set & go_set)}")

import pickle as pk

with open('CTD_gos.pkl', 'wb') as f:
    pk.dump(go_set, f)

Numero di GO in CDT: 4223
Numero di GO in UniProt: 2943
Numero di GO non attinenti a AD: 1541
Numero di GO in attinenti ad AD: 1402